name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: tests (${{ matrix.os }}, py${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Show versions
        shell: bash
        run: |
          python --version
          uv --version

      - name: Sync dependencies
        shell: bash
        run: |
          uv venv
          uv sync --dev

      - name: Run tests
        shell: bash
        run: |
          uv run pytest -q